version: "3.9"
services:
  app:
    container_name: investment_backend.app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_SIDEKIQ_URL=redis://investment_backend.redis:6379/1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    container_name: investment_backend.db
    image: postgres:15.2
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
  redis:
    container_name: investment_backend.redis
    image: redis:7.0
    volumes:
      - ./.redis:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5
  sidekiq:
    container_name: investment_backend.sidekiq
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    environment:
      - REDIS_SIDEKIQ_URL=redis://investment_backend.redis:6379/1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy