default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postgresql_username: <%= ENV.fetch("PG_USERNAME", "postgres") %>
  postgresql_password: <%= ENV.fetch("PG_PASSWORD", "postgres") %>
  postgresql_pool: <%= ENV.fetch("PG_POOL", 5) %>
  postgresql_host: <%= ENV.fetch("PG_HOST", "investment_backend.db") %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  mailer_from: <%= ENV["MAILER_FROM"] %>
  sidekiq_username: <%= ENV["SIDEKIQ_USERNAME"] %>
  sidekiq_password: <%= ENV["SIDEKIQ_PASSWORD"] %>
  redis_sidekiq_url: <%= ENV["REDIS_SIDEKIQ_URL"] %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default